### ISSUE TITLE
Porting the theme to other editors/terminals

### ISSUE THREAD

**Issue by nukeop** [challenger-deep-theme/themes#1]
Hi, amazing theme, I like it a lot.
Do you consider porting it to any other editors than emacs and vim? Perhaps to other formats like Xresources? Would you like help with that?

**Comment by tomspeak** [comment]
iTerm2 would be amazing

**Comment by MaxSt** [comment]
Thanks for the suggestion! :+1: 
Ported to [iterm](https://github.com/challenger-deep-theme/iterm) and [Xresources](https://github.com/challenger-deep-theme/xresources)
