### ISSUE TITLE
Add support for VSCode

### ISSUE THREAD

**Issue by grantbachman** [challenger-deep-theme/themes#12]
I created an extension for VSCode and would like to get it added to the list of supported editors.

Link to the repo: https://github.com/grantbachman/challenger-deep-theme

**Comment by MaxSt** [comment]
Thank you :heart:. I created a repository in the challenger-deep-theme organization and already invited you to have maintainer permissions. (https://github.com/challenger-deep-theme/vscode)
I also updated https://challenger-deep-theme.github.io/ and added the link to the repository.
