### ISSUE TITLE
Challenger deep theme for the helix editor

### ISSUE THREAD

**Issue by zSnails** [challenger-deep-theme/themes#13]
Hi! I made a port for the [helix](https://github.com/helix-editor/helix) editor
Here's the [link](https://github.com/zSnails/helix) to the repo

**Comment by MaxSt** [comment]
Thank you :heart:. I created a repository in the challenger-deep-theme organization and already invited you to have maintainer permissions. (https://github.com/challenger-deep-theme/helix)
I also updated https://challenger-deep-theme.github.io/ and added the link to the repository.
