### ISSUE TITLE
Theme made for st

### ISSUE THREAD

**Issue by JanSHoekstra** [challenger-deep-theme/themes#7]
I've made a challenger deep theme for the st terminal emulator. 
Check it out here: [Challenger Deep st](https://github.com/JanSHoekstra/Challenger-Deep-st)

**Comment by MaxSt** [comment]
Hey,
Looks good! :+1: :sunglasses: , thank you!
If you want to contribute, you can create a PR for https://github.com/challenger-deep-theme/st, which I just created in the challenger-deep github organization. As soon as your PR is merged I will add it to the website (https://challenger-deep-theme.github.io/) and to this repo.

**Comment by MaxSt** [comment]
Merged in https://github.com/challenger-deep-theme/st/pull/2.
Thank you! :+1:
