### ISSUE TITLE
Konsole Port

### ISSUE THREAD

**Issue by ChVimal** [challenger-deep-theme/themes#8]
Hi! Loved this theme in vim. 
I created a [**Konsole**](https://konsole.kde.org/) port for my use. [Here](https://github.com/ChVimal/challenger-deep-theme-konsole).
It would be great if you could create a new repo for this in the main project.

**Comment by MaxSt** [comment]
Hi,
Nice :+1: , thank you!
I created the repo in the challenger-deep github organization: https://github.com/challenger-deep-theme/Konsole. As soon as your PR is merged I will add it to the website (https://challenger-deep-theme.github.io/) and to this repo.
