### ISSUE TITLE
"Acceptable" Hex code values? License?

### ISSUE THREAD

**Issue by macintacos** [challenger-deep-theme/themes#9]
I'm thinking about porting Challenger Deep's color scheme over to [Obsidian.md](https://obsidian.md/), however I'm running into two things:

1. I think it'd be a lot more efficient if you could list the hex codes for the various colors that this theme uses so that others can contribute more easily while sticking to the original palette. I know I could just pull the colors from the dots given on [the main website](https://challenger-deep-theme.github.io/), but I was thinking of something more akin to what [Dracula does on their main repo](https://github.com/dracula/dracula-theme#color-palette).
2. There doesn't seem to be a license for this. Are contributions welcome? How would you prefer that you receive credit?

Any direction would be much appreciated. Thanks!

**Comment by MaxSt** [comment]
:heart: Thanks for the feedback!
I updated the readme to include the color palette, a FAQ section with an entry regarding contribution and a license.
